import Sidebar from "@/components/Sidebar";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { useToast, Text, Flex } from "@chakra-ui/react";

import { MdDeleteOutline } from "react-icons/md";
import axios from "axios";
import useRouter from "next/router";
import SellerCard from "../components/SellerCard";
import { isAuthenticated } from "@/helper/auth";

const Sellers = () => {
  const [sellers, setSellers] = useState([]);
  const toast = useToast();

  let auth = isAuthenticated();
  let jwt = auth.data?.jwt;
  // console.log(jwt);
  const getSellers = async () => {
    let res = await axios.get(
      "https://cloudmagician.co.in/api/seller-accounts?populate=*",
      {
        headers: {
          Authorization: `Bearer ${jwt}`,
        },
      }
    );
    setSellers(res.data.data);
    // console.log(res.data.data);
  };

  useEffect(() => {
    getSellers();
  }, []);

  return (
    <>
      <Head>
        <title>Peace Garden</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Sidebar>
          <Flex justify={"space-between"}>
            <Text fontSize={"2xl"} fontWeight={"semibold"}>
              Manage Sellers
            </Text>
          </Flex>
          <Flex justify={"space-around"} flexWrap={"wrap"}>
            {sellers.map((seller, i) => {
              return (
                <SellerCard
                  key={i}
                  sellerName={
                    seller.attributes.seller.data.attributes.first_name
                  }
                  displayName={seller.attributes.display_name}
                  data={seller}
                />
              );
            })}
            <SellerCard />
            <SellerCard />
            <SellerCard />
            <SellerCard />
          </Flex>
        </Sidebar>
      </main>
    </>
  );
};

export default Sellers;
