import Head from "next/head";
// import Image from "next/image";
import { Inter } from "next/font/google";
import {
  useToast,
  Stack,
  Text,
  Flex,
  Button,
  Input,
  Box,
  Heading,
} from "@chakra-ui/react";

import { useState } from "react";

import { useRouter } from "next/router";
import { authenticate, isAdmin, signin } from "@/helper/auth";

function Home() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState(false);
  const [values, setValues] = useState({
    loading: false,
    error: "",
  });
  const router = useRouter();
  const toast = useToast();

  const onSubmit = (event) => {
    event.preventDefault();
    setValues({ ...values, error: false, loading: true });

    signin({ email, password })
      .then((data) => {
        isAdmin(data.data.jwt).then((res) => {
          if (res.data.role.id == 5) {
            setValues({ ...values, error: false, loading: false });
            authenticate(data, () => {
              setValues({
                ...values,
                didRedirect: true,
              });
              router.push("/dashboard");
            });
          } else {
            setError("Unautharized Access");
          }
        });
      })
      .catch((err) => {
        console.log(err);
        setError("Invalid email or password");
      });
  };

  return (
    <>
      <Head>
        <title>Peace Garden Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex
          minH={"100vh"}
          align={"center"}
          justify={"center"}
          bgGradient="linear(to-l, #7928CA, #DA0155)"
        >
          <Stack spacing={8} mx={"auto"} maxW={"lg"} py={12} px={6}>
            <Box rounded={"lg"} bg="white" boxShadow="lg" p={8}>
              <Stack align={"center"}>
                <Heading>Admin Login</Heading>
              </Stack>
              <Box mt={8}>
                <form>
                  <Stack spacing={4}>
                    {error && <Text color="red">{error}</Text>}
                    <Input
                      type="email"
                      placeholder="Email"
                      isRequired
                      onChange={(event) => setEmail(event.currentTarget.value)}
                    />
                    <Input
                      type="password"
                      placeholder="Password"
                      isRequired
                      onChange={(event) =>
                        setPassword(event.currentTarget.value)
                      }
                    />

                    <Button
                      colorScheme="purple"
                      type="submit"
                      onClick={(event) => onSubmit(event)}
                    >
                      Sign in
                    </Button>
                  </Stack>
                </form>
              </Box>
            </Box>
          </Stack>
        </Flex>
      </main>
    </>
  );
}

export default Home;
