import Sidebar from "@/components/Sidebar";
import Head from "next/head";
import React from "react";
import {
  Text,
  Flex,
  Heading,
  Avatar,
  Box,
  Icon,
  Center,
  Image,
  Stack,
  Button,
  useColorModeValue,
  AvatarBadge,
} from "@chakra-ui/react";
import { Link } from "@chakra-ui/next-js";

import { MdEdit } from "react-icons/md";

const Profile = () => {
  return (
    <>
      <Head>
        <title>Peace Garden - Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Sidebar>
          <ProfileCard />
        </Sidebar>
      </main>
    </>
  );
};

const ProfileCard = () => {
  return (
    <Center py={6}>
      <Box
        maxW={"md"}
        w={"full"}
        bg={useColorModeValue("white", "gray.800")}
        boxShadow={"2xl"}
        rounded={"md"}
        overflow={"hidden"}
        display={"flex"}
        flexDirection="column"
        justify="center"
        alignItems={"center"}
      >
        <Image
          h={"120px"}
          w={"full"}
          alt="profile_pic"
          src={
            "https://images.unsplash.com/photo-1612865547334-09cb8cb455da?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80"
          }
          objectFit={"cover"}
        />
        <Flex justify={"center"} mt={-12}>
          <Avatar
            size={"xl"}
            src={
              "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1148&q=80"
            }
            alt={"Author"}
            shadow={"xl"}
            css={{
              border: "2px solid white",
            }}
          />
        </Flex>
        <Button
          bg={"transparent"}
          color={"gray"}
          textAlign={"center"}
          width={"fit-content"}
          mt="1"
        >
          Change photo
        </Button>

        <Box p={6}>
          <Stack spacing={0} align={"center"} mb={5}>
            <Heading fontSize={"2xl"} fontWeight={500} fontFamily={"body"}>
              Emiram
            </Heading>
            <Text color={"gray.500"}>iTech Enterprises</Text>
          </Stack>

          <Stack
            direction={"row"}
            justify={"space-around"}
            spacing={6}
            minWidth={"full"}
          >
            <Stack spacing={0} align={"center"}>
              <Text fontWeight={600}>23</Text>
              <Text fontSize={"sm"} color={"gray.500"}>
                Products listed
              </Text>
            </Stack>
            <Stack spacing={0} align={"center"}>
              <Text fontWeight={600}>394</Text>
              <Text fontSize={"sm"} color={"gray.500"}>
                Sold Units
              </Text>
            </Stack>
            <Stack spacing={0} align={"center"}>
              <Text fontWeight={600}>$56k</Text>
              <Text fontSize={"sm"} color={"gray.500"}>
                Net Revenue
              </Text>
            </Stack>
          </Stack>
          <Link href="/dashboard">
            <Button
              w={"full"}
              mt={8}
              bg={useColorModeValue("#151f21", "gray.900")}
              color={"white"}
              rounded={"md"}
              _hover={{
                transform: "translateY(-2px)",
                boxShadow: "lg",
              }}
            >
              View Dashboard
            </Button>
          </Link>
        </Box>
      </Box>
    </Center>
  );
};

export default Profile;
